#ifndef QUILL_RETURN_H_
#define QUILL_RETURN_H_

#define QUILL_SUCCESS 1
#define WINDOW_IS_NULL -1
#define WINDOW_PIXELS_IS_NULL -2
#define WINDOW_COLORS_IS_NULL -3

#define FAILED_WINDOW_ALLOCATION -4

#define VERTEX_OUT_OF_BOUNDS -5

#endif